services:
  minecraft:
    image: marctv/minecraft-papermc-server:1.21.4-232
    container_name: "mcserver"
    environment:
      JAVAFLAGS: "-Xms512m -Xmx12G" # выделенные ресурсы на сервер
      TZ: "Europe/Moscow"
      PAPERMC_FLAGS: "" # aikar флаги
      PUID: "1000" # выдача прав на файлы
      PGID: "1000"
      SKIP_PERM_CHECK: true
    volumes:
      - ./minecraft_data:/data  # прокидывание файлов в локальную папку (миры, плагины и т.д.)
    ports: # порт справа должен быть 25565, образ настроен под него, внешний же можно менять
      - "27000:25565"
    stdin_open: true
    tty: true